#!/bin/bash
#./runprogram --numCashiers=3 --numCustomers=100 --timePerCustomer=3
while [ $# -gt 0 ]; do
  case "$1" in
    --numCashiers=*)
      numCashiers="${1#*=}"
      ;;
    --numCustomers=*)
      numCustomers="${1#*=}"
      ;;
    --timePerCustomer=*)
			timePerCustomer="${1#*=}"
			;;

    *)
      printf "Provide arguments in the following format/sequence : --numCashiers=<numCashiers> --numCustomers=<numCustomers> --timePerCustomer=<timePerCustomer> \n"
      exit 1
  esac
  shift
 done

rm -rf build
mkdir -p build

cd src
javac BankSimulator.java -d ../build

cd ../build
java BankSimulator "$numCashiers" "$numCustomers" "$timePerCustomer"
